jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        distribution: adopt
        java-version: '8'
    - continue-on-error: true
      name: Build with Maven
      run: mvn clean install -Pgwttest
name: Java CI
on:
  repository_dispatch:
    types: trigger-ga___javaCI.yml
